### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by deniz87** [Sejemus/Tower-Unite-Piano-Bot#1]
I read the how to use notes but it doesnt actually give any clue about how to use this.
I'm new to this. Do I copy the files in to the game folder, do i use a program? Which program... Please explain. Thanks.

**Comment by OfficialHisha** [comment]
Very sorry about the long delay, I was not notified of your comment :(

This is the source code for the program, so if you just want to use the program you will have to download that on [this link](http://forums.pixeltailgames.com/clicks/track?url=https://www.dropbox.com/s/to8ycqpjaitnq60/Tower%20Unite%20Instrument%20Autoplayer%20Latest.zip?dl=0)

If you want to make improvements to the program, you can download this repository and open the .sln file in visual studio ;)

Hope this helps, and sorry for the delay!
