### ISSUE TITLE
Add WindowsInput to repository or tell us where you got it

### ISSUE THREAD

**Issue by RubenBrocke** [Sejemus/Tower-Unite-Piano-Bot#3]
When trying to understand and possibly help someone's code it's really hard if you reference a library but don't say where you got it.

requesting a link to the nuget page for other users.

**Comment by OfficialHisha** [comment]
Hello, I am using [this fork](https://inputsimulator.codeplex.com/SourceControl/network/forks/joewhaley/inputsimulator) of the WindowsInput library. I am not using the nuget package, I compiled the dll manually. Aditionally, you can find the compiled dll of WindowsInput in this solution in "Tower-Unite-Piano-Bot/Tower Unite Instrument Autoplayer/dll/". I hope this answers your question :)

A description of WindowsInput can be found on the original authors page [here](https://inputsimulator.codeplex.com/).
