### ISSUE TITLE
sending shift key

### ISSUE THREAD

**Issue by babbaj** [Sejemus/Tower-Unite-Piano-Bot#5]
To send a shift key you need to send the scancode (2C) along with the keycode.
This piano bot probably is not able to send black keys because of this but can probably be fixed if the InputSimulator library supports sending keycodes.

Heres a simple program that is able to press the black z key
```
#include <Windows.h>

int main() {
    HWND hWindowHandle = FindWindow(nullptr, "Garry's Mod");

    SendMessage(hWindowHandle, WM_KEYDOWN, VK_SHIFT, 0x002C0001);

    SendMessage(hWindowHandle, WM_KEYDOWN,'Z', 0x1);
    SendMessage(hWindowHandle, WM_KEYUP,  'Z', 0x1);

    SendMessage(hWindowHandle, WM_KEYUP, VK_SHIFT, 0x002C0001);
    return 0;
}
```

https://docs.microsoft.com/en-us/windows/desktop/inputdev/wm-keydown

**Comment by babbaj** [comment]
this fixes sending shift for gmod, not sure about tower unite

**Comment by OfficialHisha** [comment]
Hello, I appreciate the help. But the program is written in C# while the code you have provided is in C/C++ (from what I can tell).
I believe the current version, it's been a while so I may be mistaken, is able to play shift keys. It is just not able to play shift keys AND normal keys as part of the same "multinote" i.e at the same time.

I hope this makes sense and I apologize for my terribly long response time as I am not actively working on the program at this time ^^
