### ISSUE TITLE
Possible to get a release

### ISSUE THREAD

**Issue by OG5** [Sejemus/Tower-Unite-Piano-Bot#6]
Just recently wiped my pc, and dont wanna install stuff such as VS, just requesting nicely for a release of it, if this is still alive

**Comment by OfficialHisha** [comment]
Active development has stopped for now due to studies and other life stuff. I do work a little on it every once in a while. I will make a release of the latest stable version as soon as I am able to :)
Merry Christmas.

**Comment by OfficialHisha** [comment]
I apologize for the delay, but I have now made a release for the latest stable version of the program.

Enjoy :)
